// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Voo {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegateIPad")]
	public partial class AppDelegateIPad {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UILabel __mt_status;
		
		private MonoTouch.UIKit.UIButton __mt_fwdfast;
		
		private MonoTouch.UIKit.UIButton __mt_fwdslow;
		
		private MonoTouch.UIKit.UIButton __mt_louder;
		
		private MonoTouch.UIKit.UIButton __mt_play;
		
		private MonoTouch.UIKit.UIButton __mt_softer;
		
		private MonoTouch.UIKit.UIButton __mt_stop;
		
		private MonoTouch.UIKit.UIButton __mt_backslow;
		
		private MonoTouch.UIKit.UIButton __mt_backfast;
		
		private MonoTouch.UIKit.UITabBarController __mt_mainnav;
		
		private MonoTouch.UIKit.UINavigationController __mt_browsernav;
		
		private MonoTouch.UIKit.UIButton __mt_subtitles;
		
		private MonoTouch.UIKit.UIButton __mt_vol1;
		
		private MonoTouch.UIKit.UIButton __mt_vol2;
		
		private MonoTouch.UIKit.UIButton __mt_vol3;
		
		private MonoTouch.UIKit.UIButton __mt_poweroff;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("status")]
		private MonoTouch.UIKit.UILabel status {
			get {
				this.__mt_status = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("status")));
				return this.__mt_status;
			}
			set {
				this.__mt_status = value;
				this.SetNativeField("status", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("fwdfast")]
		private MonoTouch.UIKit.UIButton fwdfast {
			get {
				this.__mt_fwdfast = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("fwdfast")));
				return this.__mt_fwdfast;
			}
			set {
				this.__mt_fwdfast = value;
				this.SetNativeField("fwdfast", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("fwdslow")]
		private MonoTouch.UIKit.UIButton fwdslow {
			get {
				this.__mt_fwdslow = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("fwdslow")));
				return this.__mt_fwdslow;
			}
			set {
				this.__mt_fwdslow = value;
				this.SetNativeField("fwdslow", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("louder")]
		private MonoTouch.UIKit.UIButton louder {
			get {
				this.__mt_louder = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("louder")));
				return this.__mt_louder;
			}
			set {
				this.__mt_louder = value;
				this.SetNativeField("louder", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("play")]
		private MonoTouch.UIKit.UIButton play {
			get {
				this.__mt_play = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("play")));
				return this.__mt_play;
			}
			set {
				this.__mt_play = value;
				this.SetNativeField("play", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("softer")]
		private MonoTouch.UIKit.UIButton softer {
			get {
				this.__mt_softer = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("softer")));
				return this.__mt_softer;
			}
			set {
				this.__mt_softer = value;
				this.SetNativeField("softer", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("stop")]
		private MonoTouch.UIKit.UIButton stop {
			get {
				this.__mt_stop = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("stop")));
				return this.__mt_stop;
			}
			set {
				this.__mt_stop = value;
				this.SetNativeField("stop", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("backslow")]
		private MonoTouch.UIKit.UIButton backslow {
			get {
				this.__mt_backslow = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("backslow")));
				return this.__mt_backslow;
			}
			set {
				this.__mt_backslow = value;
				this.SetNativeField("backslow", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("backfast")]
		private MonoTouch.UIKit.UIButton backfast {
			get {
				this.__mt_backfast = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("backfast")));
				return this.__mt_backfast;
			}
			set {
				this.__mt_backfast = value;
				this.SetNativeField("backfast", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("mainnav")]
		private MonoTouch.UIKit.UITabBarController mainnav {
			get {
				this.__mt_mainnav = ((MonoTouch.UIKit.UITabBarController)(this.GetNativeField("mainnav")));
				return this.__mt_mainnav;
			}
			set {
				this.__mt_mainnav = value;
				this.SetNativeField("mainnav", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("browsernav")]
		private MonoTouch.UIKit.UINavigationController browsernav {
			get {
				this.__mt_browsernav = ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("browsernav")));
				return this.__mt_browsernav;
			}
			set {
				this.__mt_browsernav = value;
				this.SetNativeField("browsernav", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("subtitles")]
		private MonoTouch.UIKit.UIButton subtitles {
			get {
				this.__mt_subtitles = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("subtitles")));
				return this.__mt_subtitles;
			}
			set {
				this.__mt_subtitles = value;
				this.SetNativeField("subtitles", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("vol1")]
		private MonoTouch.UIKit.UIButton vol1 {
			get {
				this.__mt_vol1 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("vol1")));
				return this.__mt_vol1;
			}
			set {
				this.__mt_vol1 = value;
				this.SetNativeField("vol1", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("vol2")]
		private MonoTouch.UIKit.UIButton vol2 {
			get {
				this.__mt_vol2 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("vol2")));
				return this.__mt_vol2;
			}
			set {
				this.__mt_vol2 = value;
				this.SetNativeField("vol2", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("vol3")]
		private MonoTouch.UIKit.UIButton vol3 {
			get {
				this.__mt_vol3 = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("vol3")));
				return this.__mt_vol3;
			}
			set {
				this.__mt_vol3 = value;
				this.SetNativeField("vol3", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("poweroff")]
		private MonoTouch.UIKit.UIButton poweroff {
			get {
				this.__mt_poweroff = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("poweroff")));
				return this.__mt_poweroff;
			}
			set {
				this.__mt_poweroff = value;
				this.SetNativeField("poweroff", value);
			}
		}
	}
}
