#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Voo.Resource", IsApplication=true)]

namespace Voo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int buttonfastforward = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int buttonfastrewind = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int buttonpause = 2131034116;
			
			// aapt resource value: 0x7f050015
			public const int buttonslowforward = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int buttonslowrewind = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int buttonspeakersoff = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int buttonstop = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int buttonsubtitles = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int buttonvol1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int buttonvol65 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int buttonvol80 = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int buttonvoldown = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int buttonvolup = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int frameLayout1 = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int frameLayout2 = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout1 = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout2 = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout3 = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout4 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout5 = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout6 = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout7 = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout8 = 2131034113;
			
			// aapt resource value: 0x7f050018
			public const int textView1 = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int viewFlipper1 = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
